version: "3.9"

services:
  
  app:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: signaturit_challenge_dotnet
    volumes:
      - ./:/app
    working_dir: /app
    command: dotnet watch run --AlwaysRestartOnRudeEdit
    ports:
      - "5242:80"
